# Generated by Django 4.2.13 on 2024-07-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("createlist", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="ListOfCommonSpaces",),
    ]
