# Generated by Django 4.2.13 on 2024-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createlist", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groceriestable",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
